server:
  # SSL证书
  ssl:
    key-store: classpath:XXX.pfx
    key-store-password: XXX
    key-store-type: PKCS12

# 微信APPID
we-chat:
  appId: '微信应用ID'
  secret: '微信密钥'


spring:
  data:
    redis:
      database: 1
      host: 服务器ip地址
      port: 6379
      password: 'redis密码'
  datasource:
    url: jdbc:mysql://服务器ip地址:3306/super_bot?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true
    username: root
    password: '数据库密码'

# 管理员账号
console:
  account: '账号'
  password: '密码'


file:
  # 缓存路径 这个表示线上环境服务器 图片存储地址 如果出现上传失败 请注意检查是否拥有该文件夹的访问权限
  path: /apps/chat/resource/
  # 服务器域名
  domain: https://XXX:8624

